name: rock_n_roll_forecast
description: An app to track weather in a fashion manner for a rock'n'roll band staff.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
        - asset: assets/fonts/Satoshi-Bold.otf
        - asset: assets/fonts/Satoshi-Light.otf
        - asset: assets/fonts/Satoshi-Medium.otf
        - asset: assets/fonts/Satoshi-Regular.otf
