// Mocks generated by Mockito 5.4.4 from annotations
// in rock_n_roll_forecast/test/app/core/utilities/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:convert' as _i39;
import 'dart:typed_data' as _i40;

import 'package:connectivity_plus/connectivity_plus.dart' as _i46;
import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter/cupertino.dart' as _i16;
import 'package:flutter/foundation.dart' as _i17;
import 'package:flutter/src/services/binary_messenger.dart' as _i15;
import 'package:flutter/src/services/message_codec.dart' as _i14;
import 'package:flutter/src/services/platform_channel.dart' as _i41;
import 'package:flutter_bloc/flutter_bloc.dart' as _i20;
import 'package:hive/hive.dart' as _i13;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i43;
import 'package:hive/src/box/default_key_comparator.dart' as _i42;
import 'package:http/http.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i28;
import 'package:rock_n_roll_forecast/app/core/utilities/adapters/connectivity_adapter/connectivity_adapter.dart'
    as _i38;
import 'package:rock_n_roll_forecast/app/core/utilities/adapters/local_storage_adapter/local_storage_adapter.dart'
    as _i7;
import 'package:rock_n_roll_forecast/app/core/utilities/errors/exceptions.dart'
    as _i37;
import 'package:rock_n_roll_forecast/app/core/utilities/errors/failure.dart'
    as _i12;
import 'package:rock_n_roll_forecast/app/core/utilities/helpers/location_helper.dart'
    as _i45;
import 'package:rock_n_roll_forecast/app/core/utilities/helpers/misc_helper.dart'
    as _i44;
import 'package:rock_n_roll_forecast/app/data/datasources/local_datasource/local_datasource.dart'
    as _i8;
import 'package:rock_n_roll_forecast/app/data/datasources/local_datasource/local_datasource_impl.dart'
    as _i31;
import 'package:rock_n_roll_forecast/app/data/datasources/remote_datasources/remote_datasource.dart'
    as _i9;
import 'package:rock_n_roll_forecast/app/data/datasources/remote_datasources/remote_datasource_impl.dart'
    as _i36;
import 'package:rock_n_roll_forecast/app/data/models/forecast_model.dart'
    as _i30;
import 'package:rock_n_roll_forecast/app/data/models/weather_model.dart'
    as _i11;
import 'package:rock_n_roll_forecast/app/data/repositories/local_repository_impl.dart'
    as _i32;
import 'package:rock_n_roll_forecast/app/data/repositories/remote_repository_impl.dart'
    as _i34;
import 'package:rock_n_roll_forecast/app/domain/entities/daily_forecast_entity.dart'
    as _i6;
import 'package:rock_n_roll_forecast/app/domain/entities/location_entity.dart'
    as _i29;
import 'package:rock_n_roll_forecast/app/domain/entities/weather_entity.dart'
    as _i5;
import 'package:rock_n_roll_forecast/app/domain/repositories/local_repository.dart'
    as _i33;
import 'package:rock_n_roll_forecast/app/domain/repositories/remote_repository.dart'
    as _i35;
import 'package:rock_n_roll_forecast/app/domain/usecases/local_usecases/cache_forecast_usecase.dart'
    as _i22;
import 'package:rock_n_roll_forecast/app/domain/usecases/local_usecases/cache_weather_usecase.dart'
    as _i23;
import 'package:rock_n_roll_forecast/app/domain/usecases/local_usecases/offline_forecast_usecase.dart'
    as _i24;
import 'package:rock_n_roll_forecast/app/domain/usecases/local_usecases/offline_weather_usecase.dart'
    as _i25;
import 'package:rock_n_roll_forecast/app/domain/usecases/remote_usecases/forecast_usecase.dart'
    as _i26;
import 'package:rock_n_roll_forecast/app/domain/usecases/remote_usecases/weather_usecase.dart'
    as _i27;
import 'package:rock_n_roll_forecast/app/presentation/cubits/forecast/forecast_cubit.dart'
    as _i21;
import 'package:rock_n_roll_forecast/app/presentation/cubits/forecast/forecast_state.dart'
    as _i3;
import 'package:rock_n_roll_forecast/app/presentation/cubits/weather/weather_cubit.dart'
    as _i18;
import 'package:rock_n_roll_forecast/app/presentation/cubits/weather/weather_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherState_0 extends _i1.SmartFake implements _i2.WeatherState {
  _FakeWeatherState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastState_1 extends _i1.SmartFake implements _i3.ForecastState {
  _FakeForecastState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherEntity_3 extends _i1.SmartFake implements _i5.WeatherEntity {
  _FakeWeatherEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastEntity_4 extends _i1.SmartFake
    implements _i6.ForecastEntity {
  _FakeForecastEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalStorageAdapter_5 extends _i1.SmartFake
    implements _i7.LocalStorageAdapter {
  _FakeLocalStorageAdapter_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastLocalDatasource_6 extends _i1.SmartFake
    implements _i8.ForecastLocalDatasource {
  _FakeForecastLocalDatasource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherLocalDatasource_7 extends _i1.SmartFake
    implements _i8.WeatherLocalDatasource {
  _FakeWeatherLocalDatasource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherRemoteDatasource_8 extends _i1.SmartFake
    implements _i9.WeatherRemoteDatasource {
  _FakeWeatherRemoteDatasource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastRemoteDatasource_9 extends _i1.SmartFake
    implements _i9.ForecastRemoteDatasource {
  _FakeForecastRemoteDatasource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_10 extends _i1.SmartFake implements _i10.Client {
  _FakeClient_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherModel_11 extends _i1.SmartFake implements _i11.WeatherModel {
  _FakeWeatherModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_12 extends _i1.SmartFake implements _i12.Failure {
  _FakeFailure_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_13<E> extends _i1.SmartFake implements _i13.Box<E> {
  _FakeBox_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_14 extends _i1.SmartFake implements _i10.Response {
  _FakeResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_15 extends _i1.SmartFake
    implements _i10.StreamedResponse {
  _FakeStreamedResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMethodCodec_16 extends _i1.SmartFake implements _i14.MethodCodec {
  _FakeMethodCodec_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBinaryMessenger_17 extends _i1.SmartFake
    implements _i15.BinaryMessenger {
  _FakeBinaryMessenger_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLazyBox_18<E1> extends _i1.SmartFake implements _i13.LazyBox<E1> {
  _FakeLazyBox_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_19 extends _i1.SmartFake implements _i16.Widget {
  _FakeWidget_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i16.DiagnosticLevel? minLevel = _i16.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_20 extends _i1.SmartFake
    implements _i16.InheritedWidget {
  _FakeInheritedWidget_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i16.DiagnosticLevel? minLevel = _i16.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_21 extends _i1.SmartFake
    implements _i16.DiagnosticsNode {
  _FakeDiagnosticsNode_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i17.TextTreeConfiguration? parentConfiguration,
    _i16.DiagnosticLevel? minLevel = _i16.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [WeatherCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherCubit extends _i1.Mock implements _i18.WeatherCubit {
  MockWeatherCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWeatherState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.WeatherState);

  @override
  _i19.Stream<_i2.WeatherState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i19.Stream<_i2.WeatherState>.empty(),
      ) as _i19.Stream<_i2.WeatherState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<void> getWeather(
    String? lat,
    String? lon,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [
            lat,
            lon,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void emit(_i2.WeatherState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i20.Change<_i2.WeatherState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [ForecastCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastCubit extends _i1.Mock implements _i21.ForecastCubit {
  MockForecastCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ForecastState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeForecastState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.ForecastState);

  @override
  _i19.Stream<_i3.ForecastState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i19.Stream<_i3.ForecastState>.empty(),
      ) as _i19.Stream<_i3.ForecastState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<void> getForecast(
    String? lat,
    String? lon,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void emit(_i3.ForecastState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i20.Change<_i3.ForecastState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [CacheForecastUseCaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheForecastUseCaseImpl extends _i1.Mock
    implements _i22.CacheForecastUseCaseImpl {
  MockCacheForecastUseCaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> execute(
    List<_i6.ForecastEntity>? forecast,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            forecast,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #execute,
            [
              forecast,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);
}

/// A class which mocks [CacheWeatherUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheWeatherUsecaseImpl extends _i1.Mock
    implements _i23.CacheWeatherUsecaseImpl {
  MockCacheWeatherUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> execute(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #execute,
            [
              weather,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);
}

/// A class which mocks [OfflineForecastUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineForecastUsecaseImpl extends _i1.Mock
    implements _i24.OfflineForecastUsecaseImpl {
  MockOfflineForecastUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [OfflineWeatherUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineWeatherUsecaseImpl extends _i1.Mock
    implements _i25.OfflineWeatherUsecaseImpl {
  MockOfflineWeatherUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity?>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>);
}

/// A class which mocks [ForecastUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastUsecaseImpl extends _i1.Mock
    implements _i26.ForecastUsecaseImpl {
  MockForecastUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> execute(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherUsecaseImpl extends _i1.Mock
    implements _i27.WeatherUsecaseImpl {
  MockWeatherUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>> execute(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity>(
          this,
          Invocation.method(
            #execute,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>);
}

/// A class which mocks [CacheForecastUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheForecastUseCase extends _i1.Mock
    implements _i22.CacheForecastUseCase {
  MockCacheForecastUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> execute(
    List<_i6.ForecastEntity>? forecast,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            forecast,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #execute,
            [
              forecast,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);
}

/// A class which mocks [CacheWeatherUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheWeatherUsecase extends _i1.Mock
    implements _i23.CacheWeatherUsecase {
  MockCacheWeatherUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> execute(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #execute,
            [
              weather,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);
}

/// A class which mocks [OfflineForecastUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineForecastUsecase extends _i1.Mock
    implements _i24.OfflineForecastUsecase {
  MockOfflineForecastUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [OfflineWeatherUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineWeatherUsecase extends _i1.Mock
    implements _i25.OfflineWeatherUsecase {
  MockOfflineWeatherUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity?>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>);
}

/// A class which mocks [ForecastUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastUsecase extends _i1.Mock implements _i26.ForecastUsecase {
  MockForecastUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> execute(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherUsecase extends _i1.Mock implements _i27.WeatherUsecase {
  MockWeatherUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>> execute(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity>(
          this,
          Invocation.method(
            #execute,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>);
}

/// A class which mocks [WeatherEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherEntity extends _i1.Mock implements _i5.WeatherEntity {
  MockWeatherEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get lon => (super.noSuchMethod(
        Invocation.getter(#lon),
        returnValue: 0,
      ) as num);

  @override
  num get lat => (super.noSuchMethod(
        Invocation.getter(#lat),
        returnValue: 0,
      ) as num);

  @override
  String get main => (super.noSuchMethod(
        Invocation.getter(#main),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#main),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get iconCode => (super.noSuchMethod(
        Invocation.getter(#iconCode),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#iconCode),
        ),
      ) as String);

  @override
  int get temperature => (super.noSuchMethod(
        Invocation.getter(#temperature),
        returnValue: 0,
      ) as int);

  @override
  int get pressure => (super.noSuchMethod(
        Invocation.getter(#pressure),
        returnValue: 0,
      ) as int);

  @override
  int get humidity => (super.noSuchMethod(
        Invocation.getter(#humidity),
        returnValue: 0,
      ) as int);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [ForecastEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastEntity extends _i1.Mock implements _i6.ForecastEntity {
  MockForecastEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get dailyTime => (super.noSuchMethod(
        Invocation.getter(#dailyTime),
        returnValue: 0,
      ) as int);

  @override
  num get dailyMinTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMinTemp),
        returnValue: 0,
      ) as num);

  @override
  num get dailyMaxTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMaxTemp),
        returnValue: 0,
      ) as num);

  @override
  String get dailyIcon => (super.noSuchMethod(
        Invocation.getter(#dailyIcon),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#dailyIcon),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [CityEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCityEntity extends _i1.Mock implements _i29.CityEntity {
  MockCityEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get image => (super.noSuchMethod(
        Invocation.getter(#image),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
      ) as String);
}

/// A class which mocks [WeatherModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherModel extends _i1.Mock implements _i11.WeatherModel {
  MockWeatherModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get lon => (super.noSuchMethod(
        Invocation.getter(#lon),
        returnValue: 0,
      ) as num);

  @override
  num get lat => (super.noSuchMethod(
        Invocation.getter(#lat),
        returnValue: 0,
      ) as num);

  @override
  String get main => (super.noSuchMethod(
        Invocation.getter(#main),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#main),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get iconCode => (super.noSuchMethod(
        Invocation.getter(#iconCode),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#iconCode),
        ),
      ) as String);

  @override
  int get temperature => (super.noSuchMethod(
        Invocation.getter(#temperature),
        returnValue: 0,
      ) as int);

  @override
  int get pressure => (super.noSuchMethod(
        Invocation.getter(#pressure),
        returnValue: 0,
      ) as int);

  @override
  int get humidity => (super.noSuchMethod(
        Invocation.getter(#humidity),
        returnValue: 0,
      ) as int);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);

  @override
  _i5.WeatherEntity toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakeWeatherEntity_3(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i5.WeatherEntity);
}

/// A class which mocks [ForecastModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastModel extends _i1.Mock implements _i30.ForecastModel {
  MockForecastModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get dailyTime => (super.noSuchMethod(
        Invocation.getter(#dailyTime),
        returnValue: 0,
      ) as int);

  @override
  num get dailyMinTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMinTemp),
        returnValue: 0,
      ) as num);

  @override
  num get dailyMaxTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMaxTemp),
        returnValue: 0,
      ) as num);

  @override
  String get dailyIcon => (super.noSuchMethod(
        Invocation.getter(#dailyIcon),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#dailyIcon),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i6.ForecastEntity toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakeForecastEntity_4(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i6.ForecastEntity);
}

/// A class which mocks [WeatherLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDatasourceImpl extends _i1.Mock
    implements _i31.WeatherLocalDatasourceImpl {
  MockWeatherLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.LocalStorageAdapter get localStorageAdapter => (super.noSuchMethod(
        Invocation.getter(#localStorageAdapter),
        returnValue: _FakeLocalStorageAdapter_5(
          this,
          Invocation.getter(#localStorageAdapter),
        ),
      ) as _i7.LocalStorageAdapter);

  @override
  _i19.Future<void> cacheWeather(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i5.WeatherEntity?> offlineWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue: _i19.Future<_i5.WeatherEntity?>.value(),
      ) as _i19.Future<_i5.WeatherEntity?>);
}

/// A class which mocks [ForecastLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalDatasourceImpl extends _i1.Mock
    implements _i31.ForecastLocalDatasourceImpl {
  MockForecastLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.LocalStorageAdapter get localStorageAdapter => (super.noSuchMethod(
        Invocation.getter(#localStorageAdapter),
        returnValue: _FakeLocalStorageAdapter_5(
          this,
          Invocation.getter(#localStorageAdapter),
        ),
      ) as _i7.LocalStorageAdapter);

  @override
  _i19.Future<void> cacheForecast(
    List<_i6.ForecastEntity>? forecasts,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecasts,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<List<_i6.ForecastEntity>> offlineForecasts(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineForecasts,
          [city],
        ),
        returnValue:
            _i19.Future<List<_i6.ForecastEntity>>.value(<_i6.ForecastEntity>[]),
      ) as _i19.Future<List<_i6.ForecastEntity>>);
}

/// A class which mocks [WeatherLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDatasource extends _i1.Mock
    implements _i8.WeatherLocalDatasource {
  MockWeatherLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<void> cacheWeather(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i5.WeatherEntity?> offlineWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue: _i19.Future<_i5.WeatherEntity?>.value(),
      ) as _i19.Future<_i5.WeatherEntity?>);
}

/// A class which mocks [ForecastLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalDatasource extends _i1.Mock
    implements _i8.ForecastLocalDatasource {
  MockForecastLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<void> cacheForecast(
    List<_i6.ForecastEntity>? forecasts,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecasts,
            city,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<List<_i6.ForecastEntity>> offlineForecasts(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineForecasts,
          [city],
        ),
        returnValue:
            _i19.Future<List<_i6.ForecastEntity>>.value(<_i6.ForecastEntity>[]),
      ) as _i19.Future<List<_i6.ForecastEntity>>);
}

/// A class which mocks [ForecastLocalRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalRepositoryImpl extends _i1.Mock
    implements _i32.ForecastLocalRepositoryImpl {
  MockForecastLocalRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ForecastLocalDatasource get localDatasource => (super.noSuchMethod(
        Invocation.getter(#localDatasource),
        returnValue: _FakeForecastLocalDatasource_6(
          this,
          Invocation.getter(#localDatasource),
        ),
      ) as _i8.ForecastLocalDatasource);

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> cacheForecast(
    List<_i6.ForecastEntity>? forecast,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecast,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #cacheForecast,
            [
              forecast,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>
      offlineForecast(String? city) => (super.noSuchMethod(
            Invocation.method(
              #offlineForecast,
              [city],
            ),
            returnValue: _i19.Future<
                    _i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
                _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
              this,
              Invocation.method(
                #offlineForecast,
                [city],
              ),
            )),
          ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherLocalRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalRepositoryImpl extends _i1.Mock
    implements _i32.WeatherLocalRepositoryImpl {
  MockWeatherLocalRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.WeatherLocalDatasource get localDatasource => (super.noSuchMethod(
        Invocation.getter(#localDatasource),
        returnValue: _FakeWeatherLocalDatasource_7(
          this,
          Invocation.getter(#localDatasource),
        ),
      ) as _i8.WeatherLocalDatasource);

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> cacheWeather(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #cacheWeather,
            [
              weather,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>> offlineWeather(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity?>(
          this,
          Invocation.method(
            #offlineWeather,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>);
}

/// A class which mocks [ForecastLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalRepository extends _i1.Mock
    implements _i33.ForecastLocalRepository {
  MockForecastLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> cacheForecast(
    List<_i6.ForecastEntity>? forecasts,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecasts,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #cacheForecast,
            [
              forecasts,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>
      offlineForecast(String? city) => (super.noSuchMethod(
            Invocation.method(
              #offlineForecast,
              [city],
            ),
            returnValue: _i19.Future<
                    _i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
                _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
              this,
              Invocation.method(
                #offlineForecast,
                [city],
              ),
            )),
          ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalRepository extends _i1.Mock
    implements _i33.WeatherLocalRepository {
  MockWeatherLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, void>> cacheWeather(
    _i5.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i19.Future<_i4.Either<_i12.Failure, void>>.value(
            _FakeEither_2<_i12.Failure, void>(
          this,
          Invocation.method(
            #cacheWeather,
            [
              weather,
              city,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>> offlineWeather(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity?>(
          this,
          Invocation.method(
            #offlineWeather,
            [city],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity?>>);
}

/// A class which mocks [WeatherRemoteRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteRepositoryImpl extends _i1.Mock
    implements _i34.WeatherRemoteRepositoryImpl {
  MockWeatherRemoteRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.WeatherRemoteDatasource get remoteDatasource => (super.noSuchMethod(
        Invocation.getter(#remoteDatasource),
        returnValue: _FakeWeatherRemoteDatasource_8(
          this,
          Invocation.getter(#remoteDatasource),
        ),
      ) as _i9.WeatherRemoteDatasource);

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>> getWeather(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity>(
          this,
          Invocation.method(
            #getWeather,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>);
}

/// A class which mocks [ForecastRemoteRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteRepositoryImpl extends _i1.Mock
    implements _i34.ForecastRemoteRepositoryImpl {
  MockForecastRemoteRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ForecastRemoteDatasource get remoteDatasource => (super.noSuchMethod(
        Invocation.getter(#remoteDatasource),
        returnValue: _FakeForecastRemoteDatasource_9(
          this,
          Invocation.getter(#remoteDatasource),
        ),
      ) as _i9.ForecastRemoteDatasource);

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> getForecast(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #getForecast,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteRepository extends _i1.Mock
    implements _i35.WeatherRemoteRepository {
  MockWeatherRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>> getWeather(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>.value(
                _FakeEither_2<_i12.Failure, _i5.WeatherEntity>(
          this,
          Invocation.method(
            #getWeather,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, _i5.WeatherEntity>>);
}

/// A class which mocks [ForecastRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteRepository extends _i1.Mock
    implements _i35.ForecastRemoteRepository {
  MockForecastRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>> getForecast(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19
            .Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>.value(
            _FakeEither_2<_i12.Failure, List<_i6.ForecastEntity>>(
          this,
          Invocation.method(
            #getForecast,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Either<_i12.Failure, List<_i6.ForecastEntity>>>);
}

/// A class which mocks [WeatherRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasourceImpl extends _i1.Mock
    implements _i36.WeatherRemoteDatasourceImpl {
  MockWeatherRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_10(
          this,
          Invocation.getter(#client),
        ),
      ) as _i10.Client);

  @override
  _i19.Future<_i11.WeatherModel> getWeather(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19.Future<_i11.WeatherModel>.value(_FakeWeatherModel_11(
          this,
          Invocation.method(
            #getWeather,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i11.WeatherModel>);
}

/// A class which mocks [ForecastRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteDatasourceImpl extends _i1.Mock
    implements _i36.ForecastRemoteDatasourceImpl {
  MockForecastRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_10(
          this,
          Invocation.getter(#client),
        ),
      ) as _i10.Client);

  @override
  _i19.Future<List<_i30.ForecastModel>> getForecast(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<List<_i30.ForecastModel>>.value(<_i30.ForecastModel>[]),
      ) as _i19.Future<List<_i30.ForecastModel>>);
}

/// A class which mocks [WeatherRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasource extends _i1.Mock
    implements _i9.WeatherRemoteDatasource {
  MockWeatherRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i11.WeatherModel> getWeather(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i19.Future<_i11.WeatherModel>.value(_FakeWeatherModel_11(
          this,
          Invocation.method(
            #getWeather,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i19.Future<_i11.WeatherModel>);
}

/// A class which mocks [ForecastRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteDatasource extends _i1.Mock
    implements _i9.ForecastRemoteDatasource {
  MockForecastRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<List<_i30.ForecastModel>> getForecast(
    String? lat,
    String? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i19.Future<List<_i30.ForecastModel>>.value(<_i30.ForecastModel>[]),
      ) as _i19.Future<List<_i30.ForecastModel>>);
}

/// A class which mocks [CacheException].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheException extends _i1.Mock implements _i37.CacheException {
  MockCacheException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Failure get failure => (super.noSuchMethod(
        Invocation.getter(#failure),
        returnValue: _FakeFailure_12(
          this,
          Invocation.getter(#failure),
        ),
      ) as _i12.Failure);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [ConnectivityAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityAdapter extends _i1.Mock
    implements _i38.ConnectivityAdapter {
  MockConnectivityAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);
}

/// A class which mocks [LocalStorageAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageAdapter extends _i1.Mock
    implements _i7.LocalStorageAdapter {
  MockLocalStorageAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i13.Box<dynamic>> openBox(String? name) => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
        ),
        returnValue: _i19.Future<_i13.Box<dynamic>>.value(_FakeBox_13<dynamic>(
          this,
          Invocation.method(
            #openBox,
            [name],
          ),
        )),
      ) as _i19.Future<_i13.Box<dynamic>>);

  @override
  _i19.Future<void> put(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<dynamic> get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);

  @override
  _i19.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i10.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i10.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<_i10.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<_i10.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i39.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<_i10.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i39.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<_i10.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i39.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<_i10.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i39.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i19.Future<_i10.Response>.value(_FakeResponse_14(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i19.Future<_i10.Response>);

  @override
  _i19.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i19.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i19.Future<String>);

  @override
  _i19.Future<_i40.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i19.Future<_i40.Uint8List>.value(_i40.Uint8List(0)),
      ) as _i19.Future<_i40.Uint8List>);

  @override
  _i19.Future<_i10.StreamedResponse> send(_i10.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i19.Future<_i10.StreamedResponse>.value(_FakeStreamedResponse_15(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i19.Future<_i10.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i13.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i19.Stream<_i13.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i19.Stream<_i13.BoxEvent>.empty(),
      ) as _i19.Stream<_i13.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i19.Future<int>.value(0),
      ) as _i19.Future<int>);

  @override
  _i19.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i19.Future<Iterable<int>>.value(<int>[]),
      ) as _i19.Future<Iterable<int>>);

  @override
  _i19.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i19.Future<int>.value(0),
      ) as _i19.Future<int>);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i41.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i14.MethodCodec get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMethodCodec_16(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i14.MethodCodec);

  @override
  _i15.BinaryMessenger get binaryMessenger => (super.noSuchMethod(
        Invocation.getter(#binaryMessenger),
        returnValue: _FakeBinaryMessenger_17(
          this,
          Invocation.getter(#binaryMessenger),
        ),
      ) as _i15.BinaryMessenger);

  @override
  _i19.Future<T?> invokeMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<List<T>?> invokeListMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeListMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i19.Future<List<T>?>.value(),
      ) as _i19.Future<List<T>?>);

  @override
  _i19.Future<Map<K, V>?> invokeMapMethod<K, V>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMapMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i19.Future<Map<K, V>?>.value(),
      ) as _i19.Future<Map<K, V>?>);

  @override
  void setMethodCallHandler(
          _i19.Future<dynamic> Function(_i14.MethodCall)? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #setMethodCallHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HiveInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveInterface extends _i1.Mock implements _i13.HiveInterface {
  MockHiveInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init(
    String? path, {
    _i13.HiveStorageBackendPreference? backendPreference =
        _i13.HiveStorageBackendPreference.native,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [path],
          {#backendPreference: backendPreference},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i13.Box<E>> openBox<E>(
    String? name, {
    _i13.HiveCipher? encryptionCipher,
    _i13.KeyComparator? keyComparator = _i42.defaultKeyComparator,
    _i13.CompactionStrategy? compactionStrategy =
        _i43.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    _i40.Uint8List? bytes,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #bytes: bytes,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i19.Future<_i13.Box<E>>.value(_FakeBox_13<E>(
          this,
          Invocation.method(
            #openBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #bytes: bytes,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i19.Future<_i13.Box<E>>);

  @override
  _i19.Future<_i13.LazyBox<E>> openLazyBox<E>(
    String? name, {
    _i13.HiveCipher? encryptionCipher,
    _i13.KeyComparator? keyComparator = _i42.defaultKeyComparator,
    _i13.CompactionStrategy? compactionStrategy =
        _i43.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openLazyBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i19.Future<_i13.LazyBox<E>>.value(_FakeLazyBox_18<E>(
          this,
          Invocation.method(
            #openLazyBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i19.Future<_i13.LazyBox<E>>);

  @override
  _i13.Box<E> box<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #box,
          [name],
        ),
        returnValue: _FakeBox_13<E>(
          this,
          Invocation.method(
            #box,
            [name],
          ),
        ),
      ) as _i13.Box<E>);

  @override
  _i13.LazyBox<E> lazyBox<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #lazyBox,
          [name],
        ),
        returnValue: _FakeLazyBox_18<E>(
          this,
          Invocation.method(
            #lazyBox,
            [name],
          ),
        ),
      ) as _i13.LazyBox<E>);

  @override
  bool isBoxOpen(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isBoxOpen,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteBoxFromDisk(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBoxFromDisk,
          [name],
          {#path: path},
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  List<int> generateSecureKey() => (super.noSuchMethod(
        Invocation.method(
          #generateSecureKey,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i19.Future<bool> boxExists(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #boxExists,
          [name],
          {#path: path},
        ),
        returnValue: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  void resetAdapters() => super.noSuchMethod(
        Invocation.method(
          #resetAdapters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerAdapter<T>(
    _i13.TypeAdapter<T>? adapter, {
    bool? internal = false,
    bool? override = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerAdapter,
          [adapter],
          {
            #internal: internal,
            #override: override,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAdapterRegistered(int? typeId) => (super.noSuchMethod(
        Invocation.method(
          #isAdapterRegistered,
          [typeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void ignoreTypeId<T>(int? typeId) => super.noSuchMethod(
        Invocation.method(
          #ignoreTypeId,
          [typeId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MiscHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMiscHelper extends _i1.Mock implements _i44.MiscHelper {
  MockMiscHelper() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [LocationHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationHelper extends _i1.Mock implements _i45.LocationHelper {
  MockLocationHelper() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i16.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_19(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i16.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i16.InheritedWidget dependOnInheritedElement(
    _i16.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_20(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i16.InheritedWidget);

  @override
  void visitAncestorElements(_i16.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i16.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i16.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.DiagnosticsNode describeElement(
    String? name, {
    _i17.DiagnosticsTreeStyle? style = _i17.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_21(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i16.DiagnosticsNode);

  @override
  _i16.DiagnosticsNode describeWidget(
    String? name, {
    _i17.DiagnosticsTreeStyle? style = _i17.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_21(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i16.DiagnosticsNode);

  @override
  List<_i16.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i16.DiagnosticsNode>[],
      ) as List<_i16.DiagnosticsNode>);

  @override
  _i16.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_21(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i16.DiagnosticsNode);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i46.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Stream<_i46.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i19.Stream<_i46.ConnectivityResult>.empty(),
      ) as _i19.Stream<_i46.ConnectivityResult>);

  @override
  _i19.Future<_i46.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i19.Future<_i46.ConnectivityResult>.value(
            _i46.ConnectivityResult.bluetooth),
      ) as _i19.Future<_i46.ConnectivityResult>);
}
