// Mocks generated by Mockito 5.4.4 from annotations
// in rock_n_roll_forecast/test/app/shared/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i24;
import 'dart:convert' as _i40;
import 'dart:typed_data' as _i41;

import 'package:connectivity_plus/connectivity_plus.dart' as _i45;
import 'package:dartz/dartz.dart' as _i6;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/services.dart' as _i42;
import 'package:flutter/src/services/binary_messenger.dart' as _i20;
import 'package:flutter/src/services/message_codec.dart' as _i19;
import 'package:flutter_bloc/flutter_bloc.dart' as _i25;
import 'package:hive/hive.dart' as _i17;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i44;
import 'package:hive/src/box/default_key_comparator.dart' as _i43;
import 'package:http/http.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:rock_n_roll_forecast/app/modules/weather/data/datasources/local_datasource/forecast_local_datasource.dart'
    as _i32;
import 'package:rock_n_roll_forecast/app/modules/weather/data/datasources/local_datasource/weather_local_datasource.dart'
    as _i31;
import 'package:rock_n_roll_forecast/app/modules/weather/data/datasources/remote_datasources/forecast_remote_datasource.dart'
    as _i10;
import 'package:rock_n_roll_forecast/app/modules/weather/data/datasources/remote_datasources/weather_remote_datasource.dart'
    as _i12;
import 'package:rock_n_roll_forecast/app/modules/weather/data/models/forecast_model.dart'
    as _i30;
import 'package:rock_n_roll_forecast/app/modules/weather/data/models/weather_model.dart'
    as _i15;
import 'package:rock_n_roll_forecast/app/modules/weather/data/repositories/forecast_repository_impl.dart'
    as _i33;
import 'package:rock_n_roll_forecast/app/modules/weather/data/repositories/weather_repository_impl.dart'
    as _i34;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/entities/forecast_entity.dart'
    as _i8;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/entities/location_entity.dart'
    as _i29;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/entities/weather_entity.dart'
    as _i7;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/repositories/forecast_repository.dart'
    as _i36;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/repositories/weather_repository.dart'
    as _i35;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/usecases/forecast_usecase.dart'
    as _i27;
import 'package:rock_n_roll_forecast/app/modules/weather/domain/usecases/weather_usecase.dart'
    as _i28;
import 'package:rock_n_roll_forecast/app/modules/weather/presentation/cubits/forecast/forecast_cubit.dart'
    as _i26;
import 'package:rock_n_roll_forecast/app/modules/weather/presentation/cubits/forecast/forecast_state.dart'
    as _i5;
import 'package:rock_n_roll_forecast/app/modules/weather/presentation/cubits/weather/weather_cubit.dart'
    as _i23;
import 'package:rock_n_roll_forecast/app/modules/weather/presentation/cubits/weather/weather_state.dart'
    as _i4;
import 'package:rock_n_roll_forecast/app/modules/weather/presentation/widgets/concerts_list.dart'
    as _i21;
import 'package:rock_n_roll_forecast/app/shared/errors/exceptions.dart' as _i37;
import 'package:rock_n_roll_forecast/app/shared/errors/failure.dart' as _i16;
import 'package:rock_n_roll_forecast/app/shared/services/connectivity_service.dart'
    as _i11;
import 'package:rock_n_roll_forecast/app/shared/services/hive_service.dart'
    as _i38;
import 'package:rock_n_roll_forecast/app/shared/services/http_service.dart'
    as _i13;
import 'package:rock_n_roll_forecast/app/shared/services/local_storage_service.dart'
    as _i9;
import 'package:rock_n_roll_forecast/app/shared/services/location_service.dart'
    as _i14;
import 'package:rock_n_roll_forecast/app/shared/utilities/env_config.dart'
    as _i39;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeStatelessElement_1 extends _i1.SmartFake
    implements _i2.StatelessElement {
  _FakeStatelessElement_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i2.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeWeatherState_3 extends _i1.SmartFake implements _i4.WeatherState {
  _FakeWeatherState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastState_4 extends _i1.SmartFake implements _i5.ForecastState {
  _FakeForecastState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_5<L, R> extends _i1.SmartFake implements _i6.Either<L, R> {
  _FakeEither_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherEntity_6 extends _i1.SmartFake implements _i7.WeatherEntity {
  _FakeWeatherEntity_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastEntity_7 extends _i1.SmartFake
    implements _i8.ForecastEntity {
  _FakeForecastEntity_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalStorageService_8 extends _i1.SmartFake
    implements _i9.LocalStorageService {
  _FakeLocalStorageService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastRemoteDatasource_9 extends _i1.SmartFake
    implements _i10.ForecastRemoteDatasource {
  _FakeForecastRemoteDatasource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectivityService_10 extends _i1.SmartFake
    implements _i11.ConnectivityService {
  _FakeConnectivityService_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherRemoteDatasource_11 extends _i1.SmartFake
    implements _i12.WeatherRemoteDatasource {
  _FakeWeatherRemoteDatasource_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpService_12 extends _i1.SmartFake implements _i13.HttpService {
  _FakeHttpService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationService_13 extends _i1.SmartFake
    implements _i14.LocationService {
  _FakeLocationService_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherModel_14 extends _i1.SmartFake implements _i15.WeatherModel {
  _FakeWeatherModel_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_15 extends _i1.SmartFake implements _i16.Failure {
  _FakeFailure_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_16<E> extends _i1.SmartFake implements _i17.Box<E> {
  _FakeBox_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_17 extends _i1.SmartFake implements _i18.Response {
  _FakeResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_18 extends _i1.SmartFake
    implements _i18.StreamedResponse {
  _FakeStreamedResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMethodCodec_19 extends _i1.SmartFake implements _i19.MethodCodec {
  _FakeMethodCodec_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBinaryMessenger_20 extends _i1.SmartFake
    implements _i20.BinaryMessenger {
  _FakeBinaryMessenger_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLazyBox_21<E1> extends _i1.SmartFake implements _i17.LazyBox<E1> {
  _FakeLazyBox_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInheritedWidget_22 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ConcertsList].
///
/// See the documentation for Mockito's code generation for more information.
class MockConcertsList extends _i1.Mock implements _i21.ConcertsList {
  MockConcertsList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<dynamic> get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i2.Widget build(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #build,
          [context],
        ),
        returnValue: _FakeWidget_0(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.StatelessElement createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStatelessElement_1(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.StatelessElement);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  void debugFillProperties(_i3.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toStringShallow({
    String? joiner = r', ',
    _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = r'',
    String? prefixOtherLines,
    _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  _i2.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i3.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i2.DiagnosticsNode);

  @override
  List<_i2.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i2.DiagnosticsNode>[],
      ) as List<_i2.DiagnosticsNode>);

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [WeatherCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherCubit extends _i1.Mock implements _i23.WeatherCubit {
  MockWeatherCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.WeatherState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWeatherState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.WeatherState);

  @override
  _i24.Stream<_i4.WeatherState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i24.Stream<_i4.WeatherState>.empty(),
      ) as _i24.Stream<_i4.WeatherState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> getWeather(String? city) => (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void emit(_i4.WeatherState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i25.Change<_i4.WeatherState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);
}

/// A class which mocks [ForecastCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastCubit extends _i1.Mock implements _i26.ForecastCubit {
  MockForecastCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ForecastState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeForecastState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.ForecastState);

  @override
  _i24.Stream<_i5.ForecastState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i24.Stream<_i5.ForecastState>.empty(),
      ) as _i24.Stream<_i5.ForecastState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> getForecast(String? city) => (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void emit(_i5.ForecastState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i25.Change<_i5.ForecastState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);
}

/// A class which mocks [ForecastUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastUsecaseImpl extends _i1.Mock
    implements _i27.ForecastUsecaseImpl {
  MockForecastUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue: _i24
            .Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>.value(
            _FakeEither_5<_i16.Failure, List<_i8.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>);
}

/// A class which mocks [WeatherUsecaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherUsecaseImpl extends _i1.Mock
    implements _i28.WeatherUsecaseImpl {
  MockWeatherUsecaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue:
            _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>.value(
                _FakeEither_5<_i16.Failure, _i7.WeatherEntity>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>);
}

/// A class which mocks [ForecastUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastUsecase extends _i1.Mock implements _i27.ForecastUsecase {
  MockForecastUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue: _i24
            .Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>.value(
            _FakeEither_5<_i16.Failure, List<_i8.ForecastEntity>>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>);
}

/// A class which mocks [WeatherUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherUsecase extends _i1.Mock implements _i28.WeatherUsecase {
  MockWeatherUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>> execute(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue:
            _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>.value(
                _FakeEither_5<_i16.Failure, _i7.WeatherEntity>(
          this,
          Invocation.method(
            #execute,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>);
}

/// A class which mocks [WeatherEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherEntity extends _i1.Mock implements _i7.WeatherEntity {
  MockWeatherEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get lon => (super.noSuchMethod(
        Invocation.getter(#lon),
        returnValue: 0.0,
      ) as double);

  @override
  double get lat => (super.noSuchMethod(
        Invocation.getter(#lat),
        returnValue: 0.0,
      ) as double);

  @override
  double get wind => (super.noSuchMethod(
        Invocation.getter(#wind),
        returnValue: 0.0,
      ) as double);

  @override
  double get feelsLike => (super.noSuchMethod(
        Invocation.getter(#feelsLike),
        returnValue: 0.0,
      ) as double);

  @override
  String get main => (super.noSuchMethod(
        Invocation.getter(#main),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#main),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get iconCode => (super.noSuchMethod(
        Invocation.getter(#iconCode),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#iconCode),
        ),
      ) as String);

  @override
  int get temperature => (super.noSuchMethod(
        Invocation.getter(#temperature),
        returnValue: 0,
      ) as int);

  @override
  int get humidity => (super.noSuchMethod(
        Invocation.getter(#humidity),
        returnValue: 0,
      ) as int);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [ForecastEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastEntity extends _i1.Mock implements _i8.ForecastEntity {
  MockForecastEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get dailyTime => (super.noSuchMethod(
        Invocation.getter(#dailyTime),
        returnValue: 0,
      ) as int);

  @override
  num get dailyMinTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMinTemp),
        returnValue: 0,
      ) as num);

  @override
  num get dailyMaxTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMaxTemp),
        returnValue: 0,
      ) as num);

  @override
  String get dailyIcon => (super.noSuchMethod(
        Invocation.getter(#dailyIcon),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#dailyIcon),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [LocationEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationEntity extends _i1.Mock implements _i29.LocationEntity {
  MockLocationEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get city => (super.noSuchMethod(
        Invocation.getter(#city),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#city),
        ),
      ) as String);

  @override
  String get country => (super.noSuchMethod(
        Invocation.getter(#country),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#country),
        ),
      ) as String);
}

/// A class which mocks [WeatherModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherModel extends _i1.Mock implements _i15.WeatherModel {
  MockWeatherModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get lon => (super.noSuchMethod(
        Invocation.getter(#lon),
        returnValue: 0.0,
      ) as double);

  @override
  double get lat => (super.noSuchMethod(
        Invocation.getter(#lat),
        returnValue: 0.0,
      ) as double);

  @override
  double get wind => (super.noSuchMethod(
        Invocation.getter(#wind),
        returnValue: 0.0,
      ) as double);

  @override
  double get feelsLike => (super.noSuchMethod(
        Invocation.getter(#feelsLike),
        returnValue: 0.0,
      ) as double);

  @override
  String get main => (super.noSuchMethod(
        Invocation.getter(#main),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#main),
        ),
      ) as String);

  @override
  String get iconCode => (super.noSuchMethod(
        Invocation.getter(#iconCode),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#iconCode),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  int get temperature => (super.noSuchMethod(
        Invocation.getter(#temperature),
        returnValue: 0,
      ) as int);

  @override
  int get humidity => (super.noSuchMethod(
        Invocation.getter(#humidity),
        returnValue: 0,
      ) as int);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);

  @override
  _i7.WeatherEntity toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakeWeatherEntity_6(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i7.WeatherEntity);
}

/// A class which mocks [ForecastModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastModel extends _i1.Mock implements _i30.ForecastModel {
  MockForecastModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get dailyTime => (super.noSuchMethod(
        Invocation.getter(#dailyTime),
        returnValue: 0,
      ) as int);

  @override
  num get dailyMinTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMinTemp),
        returnValue: 0,
      ) as num);

  @override
  num get dailyMaxTemp => (super.noSuchMethod(
        Invocation.getter(#dailyMaxTemp),
        returnValue: 0,
      ) as num);

  @override
  String get dailyIcon => (super.noSuchMethod(
        Invocation.getter(#dailyIcon),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#dailyIcon),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i8.ForecastEntity toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakeForecastEntity_7(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i8.ForecastEntity);
}

/// A class which mocks [WeatherLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDatasourceImpl extends _i1.Mock
    implements _i31.WeatherLocalDatasourceImpl {
  MockWeatherLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LocalStorageService get localStorageService => (super.noSuchMethod(
        Invocation.getter(#localStorageService),
        returnValue: _FakeLocalStorageService_8(
          this,
          Invocation.getter(#localStorageService),
        ),
      ) as _i9.LocalStorageService);

  @override
  _i24.Future<void> cacheWeather(
    _i7.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i7.WeatherEntity> offlineWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue: _i24.Future<_i7.WeatherEntity>.value(_FakeWeatherEntity_6(
          this,
          Invocation.method(
            #offlineWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i7.WeatherEntity>);
}

/// A class which mocks [ForecastLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalDatasourceImpl extends _i1.Mock
    implements _i32.ForecastLocalDatasourceImpl {
  MockForecastLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LocalStorageService get localStorageService => (super.noSuchMethod(
        Invocation.getter(#localStorageService),
        returnValue: _FakeLocalStorageService_8(
          this,
          Invocation.getter(#localStorageService),
        ),
      ) as _i9.LocalStorageService);

  @override
  _i24.Future<void> cacheForecast(
    List<_i8.ForecastEntity>? forecasts,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecasts,
            city,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i8.ForecastEntity>> offlineForecasts(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineForecasts,
          [city],
        ),
        returnValue:
            _i24.Future<List<_i8.ForecastEntity>>.value(<_i8.ForecastEntity>[]),
      ) as _i24.Future<List<_i8.ForecastEntity>>);
}

/// A class which mocks [WeatherLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDatasource extends _i1.Mock
    implements _i31.WeatherLocalDatasource {
  MockWeatherLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<void> cacheWeather(
    _i7.WeatherEntity? weather,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            weather,
            city,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i7.WeatherEntity> offlineWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineWeather,
          [city],
        ),
        returnValue: _i24.Future<_i7.WeatherEntity>.value(_FakeWeatherEntity_6(
          this,
          Invocation.method(
            #offlineWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i7.WeatherEntity>);
}

/// A class which mocks [ForecastLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastLocalDatasource extends _i1.Mock
    implements _i32.ForecastLocalDatasource {
  MockForecastLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<void> cacheForecast(
    List<_i8.ForecastEntity>? forecasts,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            forecasts,
            city,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i8.ForecastEntity>> offlineForecasts(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #offlineForecasts,
          [city],
        ),
        returnValue:
            _i24.Future<List<_i8.ForecastEntity>>.value(<_i8.ForecastEntity>[]),
      ) as _i24.Future<List<_i8.ForecastEntity>>);
}

/// A class which mocks [ForecastRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRepositoryImpl extends _i1.Mock
    implements _i33.ForecastRepositoryImpl {
  MockForecastRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ForecastRemoteDatasource get remoteDatasource => (super.noSuchMethod(
        Invocation.getter(#remoteDatasource),
        returnValue: _FakeForecastRemoteDatasource_9(
          this,
          Invocation.getter(#remoteDatasource),
        ),
      ) as _i10.ForecastRemoteDatasource);

  @override
  _i11.ConnectivityService get connectivityService => (super.noSuchMethod(
        Invocation.getter(#connectivityService),
        returnValue: _FakeConnectivityService_10(
          this,
          Invocation.getter(#connectivityService),
        ),
      ) as _i11.ConnectivityService);

  @override
  _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>> getForecast(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
        ),
        returnValue: _i24
            .Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>.value(
            _FakeEither_5<_i16.Failure, List<_i8.ForecastEntity>>(
          this,
          Invocation.method(
            #getForecast,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>);
}

/// A class which mocks [WeatherRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepositoryImpl extends _i1.Mock
    implements _i34.WeatherRepositoryImpl {
  MockWeatherRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.WeatherRemoteDatasource get remoteDatasource => (super.noSuchMethod(
        Invocation.getter(#remoteDatasource),
        returnValue: _FakeWeatherRemoteDatasource_11(
          this,
          Invocation.getter(#remoteDatasource),
        ),
      ) as _i12.WeatherRemoteDatasource);

  @override
  _i11.ConnectivityService get connectivityService => (super.noSuchMethod(
        Invocation.getter(#connectivityService),
        returnValue: _FakeConnectivityService_10(
          this,
          Invocation.getter(#connectivityService),
        ),
      ) as _i11.ConnectivityService);

  @override
  _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>> getWeather(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue:
            _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>.value(
                _FakeEither_5<_i16.Failure, _i7.WeatherEntity>(
          this,
          Invocation.method(
            #getWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i35.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>> getWeather(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue:
            _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>.value(
                _FakeEither_5<_i16.Failure, _i7.WeatherEntity>(
          this,
          Invocation.method(
            #getWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, _i7.WeatherEntity>>);
}

/// A class which mocks [ForecastRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRepository extends _i1.Mock
    implements _i36.ForecastRepository {
  MockForecastRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>> getForecast(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
        ),
        returnValue: _i24
            .Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>.value(
            _FakeEither_5<_i16.Failure, List<_i8.ForecastEntity>>(
          this,
          Invocation.method(
            #getForecast,
            [city],
          ),
        )),
      ) as _i24.Future<_i6.Either<_i16.Failure, List<_i8.ForecastEntity>>>);
}

/// A class which mocks [WeatherRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasourceImpl extends _i1.Mock
    implements _i12.WeatherRemoteDatasourceImpl {
  MockWeatherRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.HttpService get http => (super.noSuchMethod(
        Invocation.getter(#http),
        returnValue: _FakeHttpService_12(
          this,
          Invocation.getter(#http),
        ),
      ) as _i13.HttpService);

  @override
  _i14.LocationService get locationService => (super.noSuchMethod(
        Invocation.getter(#locationService),
        returnValue: _FakeLocationService_13(
          this,
          Invocation.getter(#locationService),
        ),
      ) as _i14.LocationService);

  @override
  _i11.ConnectivityService get connectivityService => (super.noSuchMethod(
        Invocation.getter(#connectivityService),
        returnValue: _FakeConnectivityService_10(
          this,
          Invocation.getter(#connectivityService),
        ),
      ) as _i11.ConnectivityService);

  @override
  _i24.Future<_i15.WeatherModel> getWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue: _i24.Future<_i15.WeatherModel>.value(_FakeWeatherModel_14(
          this,
          Invocation.method(
            #getWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i15.WeatherModel>);
}

/// A class which mocks [ForecastRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteDatasourceImpl extends _i1.Mock
    implements _i10.ForecastRemoteDatasourceImpl {
  MockForecastRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.HttpService get http => (super.noSuchMethod(
        Invocation.getter(#http),
        returnValue: _FakeHttpService_12(
          this,
          Invocation.getter(#http),
        ),
      ) as _i13.HttpService);

  @override
  _i14.LocationService get locationService => (super.noSuchMethod(
        Invocation.getter(#locationService),
        returnValue: _FakeLocationService_13(
          this,
          Invocation.getter(#locationService),
        ),
      ) as _i14.LocationService);

  @override
  _i11.ConnectivityService get connectivityService => (super.noSuchMethod(
        Invocation.getter(#connectivityService),
        returnValue: _FakeConnectivityService_10(
          this,
          Invocation.getter(#connectivityService),
        ),
      ) as _i11.ConnectivityService);

  @override
  _i24.Future<List<_i30.ForecastModel>> getForecast(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
        ),
        returnValue:
            _i24.Future<List<_i30.ForecastModel>>.value(<_i30.ForecastModel>[]),
      ) as _i24.Future<List<_i30.ForecastModel>>);
}

/// A class which mocks [WeatherRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasource extends _i1.Mock
    implements _i12.WeatherRemoteDatasource {
  MockWeatherRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i15.WeatherModel> getWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue: _i24.Future<_i15.WeatherModel>.value(_FakeWeatherModel_14(
          this,
          Invocation.method(
            #getWeather,
            [city],
          ),
        )),
      ) as _i24.Future<_i15.WeatherModel>);
}

/// A class which mocks [ForecastRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastRemoteDatasource extends _i1.Mock
    implements _i10.ForecastRemoteDatasource {
  MockForecastRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<List<_i30.ForecastModel>> getForecast(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
        ),
        returnValue:
            _i24.Future<List<_i30.ForecastModel>>.value(<_i30.ForecastModel>[]),
      ) as _i24.Future<List<_i30.ForecastModel>>);
}

/// A class which mocks [CacheException].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheException extends _i1.Mock implements _i37.CacheException {
  MockCacheException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Failure get failure => (super.noSuchMethod(
        Invocation.getter(#failure),
        returnValue: _FakeFailure_15(
          this,
          Invocation.getter(#failure),
        ),
      ) as _i16.Failure);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i11.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i38.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i17.Box<dynamic>> openBox(String? name) => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
        ),
        returnValue: _i24.Future<_i17.Box<dynamic>>.value(_FakeBox_16<dynamic>(
          this,
          Invocation.method(
            #openBox,
            [name],
          ),
        )),
      ) as _i24.Future<_i17.Box<dynamic>>);

  @override
  _i24.Future<void> put(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<dynamic> get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  _i24.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i13.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<Map<String, dynamic>> getRequest(
    String? url, {
    Map<String, String>? headers,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [url],
          {
            #headers: headers,
            #errorMessage: errorMessage,
          },
        ),
        returnValue:
            _i24.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i24.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i9.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<void> cacheRequest(
    String? boxName,
    dynamic data,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheRequest,
          [
            boxName,
            data,
            city,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<dynamic> getRequest(
    String? boxName,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [
            boxName,
            city,
          ],
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i14.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<Map<String, double>> getCoordinates(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoordinates,
          [city],
        ),
        returnValue: _i24.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i24.Future<Map<String, double>>);
}

/// A class which mocks [EnvConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvConfig extends _i1.Mock implements _i39.EnvConfig {
  MockEnvConfig() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i18.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i18.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<_i18.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<_i18.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i40.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<_i18.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i40.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<_i18.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i40.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<_i18.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i40.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i18.Response>.value(_FakeResponse_17(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i18.Response>);

  @override
  _i24.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<_i41.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i41.Uint8List>.value(_i41.Uint8List(0)),
      ) as _i24.Future<_i41.Uint8List>);

  @override
  _i24.Future<_i18.StreamedResponse> send(_i18.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i24.Future<_i18.StreamedResponse>.value(_FakeStreamedResponse_18(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i24.Future<_i18.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i17.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i24.Stream<_i17.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i24.Stream<_i17.BoxEvent>.empty(),
      ) as _i24.Stream<_i17.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i24.Future<Iterable<int>>.value(<int>[]),
      ) as _i24.Future<Iterable<int>>);

  @override
  _i24.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i42.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i19.MethodCodec get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMethodCodec_19(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i19.MethodCodec);

  @override
  _i20.BinaryMessenger get binaryMessenger => (super.noSuchMethod(
        Invocation.getter(#binaryMessenger),
        returnValue: _FakeBinaryMessenger_20(
          this,
          Invocation.getter(#binaryMessenger),
        ),
      ) as _i20.BinaryMessenger);

  @override
  _i24.Future<T?> invokeMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i24.Future<T?>.value(),
      ) as _i24.Future<T?>);

  @override
  _i24.Future<List<T>?> invokeListMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeListMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i24.Future<List<T>?>.value(),
      ) as _i24.Future<List<T>?>);

  @override
  _i24.Future<Map<K, V>?> invokeMapMethod<K, V>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMapMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i24.Future<Map<K, V>?>.value(),
      ) as _i24.Future<Map<K, V>?>);

  @override
  void setMethodCallHandler(
          _i24.Future<dynamic> Function(_i19.MethodCall)? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #setMethodCallHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HiveInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveInterface extends _i1.Mock implements _i17.HiveInterface {
  MockHiveInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init(
    String? path, {
    _i17.HiveStorageBackendPreference? backendPreference =
        _i17.HiveStorageBackendPreference.native,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [path],
          {#backendPreference: backendPreference},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<_i17.Box<E>> openBox<E>(
    String? name, {
    _i17.HiveCipher? encryptionCipher,
    _i17.KeyComparator? keyComparator = _i43.defaultKeyComparator,
    _i17.CompactionStrategy? compactionStrategy =
        _i44.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    _i41.Uint8List? bytes,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #bytes: bytes,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i24.Future<_i17.Box<E>>.value(_FakeBox_16<E>(
          this,
          Invocation.method(
            #openBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #bytes: bytes,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i24.Future<_i17.Box<E>>);

  @override
  _i24.Future<_i17.LazyBox<E>> openLazyBox<E>(
    String? name, {
    _i17.HiveCipher? encryptionCipher,
    _i17.KeyComparator? keyComparator = _i43.defaultKeyComparator,
    _i17.CompactionStrategy? compactionStrategy =
        _i44.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openLazyBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i24.Future<_i17.LazyBox<E>>.value(_FakeLazyBox_21<E>(
          this,
          Invocation.method(
            #openLazyBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i24.Future<_i17.LazyBox<E>>);

  @override
  _i17.Box<E> box<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #box,
          [name],
        ),
        returnValue: _FakeBox_16<E>(
          this,
          Invocation.method(
            #box,
            [name],
          ),
        ),
      ) as _i17.Box<E>);

  @override
  _i17.LazyBox<E> lazyBox<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #lazyBox,
          [name],
        ),
        returnValue: _FakeLazyBox_21<E>(
          this,
          Invocation.method(
            #lazyBox,
            [name],
          ),
        ),
      ) as _i17.LazyBox<E>);

  @override
  bool isBoxOpen(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isBoxOpen,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteBoxFromDisk(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBoxFromDisk,
          [name],
          {#path: path},
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  List<int> generateSecureKey() => (super.noSuchMethod(
        Invocation.method(
          #generateSecureKey,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i24.Future<bool> boxExists(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #boxExists,
          [name],
          {#path: path},
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  void resetAdapters() => super.noSuchMethod(
        Invocation.method(
          #resetAdapters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerAdapter<T>(
    _i17.TypeAdapter<T>? adapter, {
    bool? internal = false,
    bool? override = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerAdapter,
          [adapter],
          {
            #internal: internal,
            #override: override,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAdapterRegistered(int? typeId) => (super.noSuchMethod(
        Invocation.method(
          #isAdapterRegistered,
          [typeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void ignoreTypeId<T>(int? typeId) => super.noSuchMethod(
        Invocation.method(
          #ignoreTypeId,
          [typeId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_22(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i2.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i2.DiagnosticsNode);

  @override
  _i2.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i2.DiagnosticsNode);

  @override
  List<_i2.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i2.DiagnosticsNode>[],
      ) as List<_i2.DiagnosticsNode>);

  @override
  _i2.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i2.DiagnosticsNode);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i45.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Stream<_i45.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i24.Stream<_i45.ConnectivityResult>.empty(),
      ) as _i24.Stream<_i45.ConnectivityResult>);

  @override
  _i24.Future<_i45.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i24.Future<_i45.ConnectivityResult>.value(
            _i45.ConnectivityResult.bluetooth),
      ) as _i24.Future<_i45.ConnectivityResult>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i2.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i2.Route<dynamic>? route,
    _i2.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i2.Route<dynamic>? route,
    _i2.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i2.Route<dynamic>? route,
    _i2.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i2.Route<dynamic>? newRoute,
    _i2.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i2.Route<dynamic>? route,
    _i2.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RouteSettings].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockRouteSettings extends _i1.Mock implements _i2.RouteSettings {
  MockRouteSettings() {
    _i1.throwOnMissingStub(this);
  }
}
